./" *************************************************************************
./"     gwb.1：gwb(1)手冊頁。
./"     版權 (C) 2023 gsm <406643764@qq.com>
./"     本程序為自由軟件：你可以依據自由軟件基金會所發布的第三版或更高版本的
./" GNU通用公共許可證重新發布、修改本程序。
./"     雖然基于使用目的而發布本程序，但不負任何擔保責任，亦不包含適銷性或特
./" 定目標之適用性的暗示性擔保。詳見GNU通用公共許可證。
./"     你應該已經收到一份附隨此程序的GNU通用公共許可證副本。否則，請參閱
./" <http://www.gnu.org/licenses/>。
./" ************************************************************************/
.TH gwb 1 2023年1月 "gwb 0.1" gwb
.
.SH 名稱
gwb \- gwb（gsm's web browser），是一個用C語言編寫的基於webkitgtk的網頁瀏覽器。
.
.SH 摘要
.B gwb [URI]
.
.SH 描述
.PP
gwb（gsm's web browser），是一個用C語言編寫的基於webkitgtk的網頁瀏覽器。
.
.SH 選項
無。
.
.SH 用法
.
.SS 通用說明
.
.TP
不帶參數或以多個參數運行gwb，將打開默認網頁。用一個指定的URI作爲參數運行gwb，則會打開該URI。
.
.SS 鍵盤命令
.
.TP
.B 暫無。
.
.SS 定位器命令
.
.TP
.B 暫無。
.
.SS 配置
.
.TP
目前只能通過修改源代碼來修改配置。具體是修改gwb.c。
.
.SH 漏洞報告
.
若你發現漏洞，則請向<406643764@qq.com>報告。
.
.SH 作者
.
此程序由gsm<406643764@qq.com>開發。
.br
官方網站：https://sourceforge.net/projects/gwb/。
.
.SH 版權
.
版權 \(co 2023 gsm <406643764@qq.com>。
.br
本程序為自由軟件：你可以依據自由軟件基金會所發布的第三版或更高版本的GNU通用公共許可證重新發布、修改本程序。
