./" *************************************************************************
./"     gwb.1：gwb(1)手冊頁。
./"     版權 (C) 2023 gsm <406643764@qq.com>
./"     本程序為自由軟件：你可以依據自由軟件基金會所發布的第三版或更高版本的
./" GNU通用公共許可證重新發布、修改本程序。
./"     雖然基于使用目的而發布本程序，但不負任何擔保責任，亦不包含適銷性或特
./" 定目標之適用性的暗示性擔保。詳見GNU通用公共許可證。
./"     你應該已經收到一份附隨此程序的GNU通用公共許可證副本。否則，請參閱
./" <http://www.gnu.org/licenses/>。
./" ************************************************************************/
.TH gwb 1 2023年1月 "gwb 0.5" gwb
.
.SH 名稱
gwb \- gwb（gsm's web browser），是一個用C語言編寫的基於webkitgtk的網頁瀏覽器。
.
.SH 摘要
.B gwb [URI]...
.
.SH 描述
.PP
gwb（gsm's web browser），是一個用C語言編寫的基於webkitgtk的網頁瀏覽器。它的特色是極度輕量、簡潔。
.
.SH 選項
無。
.
.SH 用法
.
.SS 通用說明
.
.TP
不帶參數運行gwb，將打開主頁。用指定的URI列表作爲參數運行gwb，則會打開這些URI。譬如：gwb bing.com或gwb bing.com baidu.com。
.
.SS 鍵盤命令
.
.TP
.B 暫無。
.
.SS 定位器命令
.
.TP
定位器按鈕1通常是鼠標左鍵，定位器按鈕2通常是鼠標中鍵，定位器按鈕3通常是鼠標右鍵。
.
.TP
.B 定位器按鈕1 - 單擊。
    標籤頁“×”按鈕：關鍵該標籤頁，若僅餘一個標籤頁，則退出程序；
    標籤欄“+”按鈕：新建標籤頁；
    搜索欄：打開輸入的URI；
    書籤按鈕：打開該收藏的書籤；
    標籤欄“<”按鈕：後退，即在當前標籤頁加載當前標籤頁的上一個URI；
    標籤欄“>”按鈕：前進，即在當前標籤頁加載當前標籤頁的下一個URI；
    標籤欄“⟳”按鈕：刷新，即在當前標籤頁重新加載當前標籤頁的當前URI；
    標籤欄“⌂”按鈕：在當前標籤頁加載主頁。
.
.SS 配置
.
.TP
目前只能通過修改源代碼來修改配置。具體是修改config.h。
.
.SH 漏洞報告
.
若你發現漏洞，則請向<406643764@qq.com>或<https://sourceforge.net/p/gwb/tickets/>報告。
.
.SH 作者
.
此程序由gsm<406643764@qq.com>開發。
.br
官方網站：<https://sourceforge.net/projects/gwb/>。
.
.SH 版權
.
版權 \(co 2023 gsm <406643764@qq.com>。
.br
本程序為自由軟件：你可以依據自由軟件基金會所發布的第三版或更高版本的GNU通用公共許可證重新發布、修改本程序。
